apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcssource-controller
  namespace: gcssource-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcssource-webhook
  namespace: gcssource-system
