// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventProperties) DeepCopyInto(out *CloudEventProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventProperties.
func (in *CloudEventProperties) DeepCopy() *CloudEventProperties {
	if in == nil {
		return nil
	}
	out := new(CloudEventProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSEventTypes) DeepCopyInto(out *GCSEventTypes) {
	*out = *in
	if in.Finalize != nil {
		in, out := &in.Finalize, &out.Finalize
		*out = new(GCSObjectFinalize)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(GCSObjectDelete)
		**out = **in
	}
	if in.Archive != nil {
		in, out := &in.Archive, &out.Archive
		*out = new(GCSObjectArchive)
		**out = **in
	}
	if in.MetadataUpdate != nil {
		in, out := &in.MetadataUpdate, &out.MetadataUpdate
		*out = new(GCSMetadataUpdate)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSEventTypes.
func (in *GCSEventTypes) DeepCopy() *GCSEventTypes {
	if in == nil {
		return nil
	}
	out := new(GCSEventTypes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSMetadataUpdate) DeepCopyInto(out *GCSMetadataUpdate) {
	*out = *in
	out.CloudEventProperties = in.CloudEventProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSMetadataUpdate.
func (in *GCSMetadataUpdate) DeepCopy() *GCSMetadataUpdate {
	if in == nil {
		return nil
	}
	out := new(GCSMetadataUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSObjectArchive) DeepCopyInto(out *GCSObjectArchive) {
	*out = *in
	out.CloudEventProperties = in.CloudEventProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSObjectArchive.
func (in *GCSObjectArchive) DeepCopy() *GCSObjectArchive {
	if in == nil {
		return nil
	}
	out := new(GCSObjectArchive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSObjectDelete) DeepCopyInto(out *GCSObjectDelete) {
	*out = *in
	out.CloudEventProperties = in.CloudEventProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSObjectDelete.
func (in *GCSObjectDelete) DeepCopy() *GCSObjectDelete {
	if in == nil {
		return nil
	}
	out := new(GCSObjectDelete)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSObjectFinalize) DeepCopyInto(out *GCSObjectFinalize) {
	*out = *in
	out.CloudEventProperties = in.CloudEventProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSObjectFinalize.
func (in *GCSObjectFinalize) DeepCopy() *GCSObjectFinalize {
	if in == nil {
		return nil
	}
	out := new(GCSObjectFinalize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSSource) DeepCopyInto(out *GCSSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSSource.
func (in *GCSSource) DeepCopy() *GCSSource {
	if in == nil {
		return nil
	}
	out := new(GCSSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCSSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSSourceList) DeepCopyInto(out *GCSSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCSSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSSourceList.
func (in *GCSSourceList) DeepCopy() *GCSSourceList {
	if in == nil {
		return nil
	}
	out := new(GCSSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCSSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSSourceSpec) DeepCopyInto(out *GCSSourceSpec) {
	*out = *in
	in.GCSCredsSecret.DeepCopyInto(&out.GCSCredsSecret)
	if in.GcpCredsSecret != nil {
		in, out := &in.GcpCredsSecret, &out.GcpCredsSecret
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EventTypes != nil {
		in, out := &in.EventTypes, &out.EventTypes
		*out = new(GCSEventTypes)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomAttributes != nil {
		in, out := &in.CustomAttributes, &out.CustomAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Sink != nil {
		in, out := &in.Sink, &out.Sink
		*out = new(v1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSSourceSpec.
func (in *GCSSourceSpec) DeepCopy() *GCSSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GCSSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSSourceStatus) DeepCopyInto(out *GCSSourceStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSSourceStatus.
func (in *GCSSourceStatus) DeepCopy() *GCSSourceStatus {
	if in == nil {
		return nil
	}
	out := new(GCSSourceStatus)
	in.DeepCopyInto(out)
	return out
}
